/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashWorkersRouteImport } from './routes/dash/workers'
import { Route as DashVaultRouteImport } from './routes/dash/vault'
import { Route as DashUsenetRouteImport } from './routes/dash/usenet'
import { Route as DashTorrentRouteImport } from './routes/dash/torrent'
import { Route as DashSyncRouteImport } from './routes/dash/sync'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashProxyRouteImport } from './routes/dash/proxy'
import { Route as DashLoginRouteImport } from './routes/dash/login'
import { Route as DashListsRouteImport } from './routes/dash/lists'
import { Route as DashVaultIndexRouteImport } from './routes/dash/vault/index'
import { Route as DashUsenetIndexRouteImport } from './routes/dash/usenet/index'
import { Route as DashTorrentIndexRouteImport } from './routes/dash/torrent/index'
import { Route as DashSyncIndexRouteImport } from './routes/dash/sync/index'
import { Route as DashSettingsIndexRouteImport } from './routes/dash/settings/index'
import { Route as DashListsIndexRouteImport } from './routes/dash/lists/index'
import { Route as DashVaultTraktAccountsRouteImport } from './routes/dash/vault/trakt-accounts'
import { Route as DashVaultStremioAccountsRouteImport } from './routes/dash/vault/stremio-accounts'
import { Route as DashUsenetServersRouteImport } from './routes/dash/usenet/servers'
import { Route as DashUsenetNzbQueueRouteImport } from './routes/dash/usenet/nzb-queue'
import { Route as DashUsenetNzbInspectorRouteImport } from './routes/dash/usenet/nzb-inspector'
import { Route as DashUsenetNzbRouteImport } from './routes/dash/usenet/nzb'
import { Route as DashUsenetIndexersRouteImport } from './routes/dash/usenet/indexers'
import { Route as DashTorrentTorznabIndexersRouteImport } from './routes/dash/torrent/torznab-indexers'
import { Route as DashTorrentSyncInfoRouteImport } from './routes/dash/torrent/sync-info'
import { Route as DashTorrentInfoRouteImport } from './routes/dash/torrent/info'
import { Route as DashSyncStremioTraktRouteImport } from './routes/dash/sync/stremio-trakt'
import { Route as DashSyncStremioStremioRouteImport } from './routes/dash/sync/stremio-stremio'
import { Route as DashSettingsRatelimitConfigsRouteImport } from './routes/dash/settings/ratelimit-configs'
import { Route as DashSettingsMaintenanceRouteImport } from './routes/dash/settings/maintenance'
import { Route as DashSettingsJackettRouteImport } from './routes/dash/settings/jackett'
import { Route as DashSettingsConfigRouteImport } from './routes/dash/settings/config'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkersRoute = DashWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashRoute,
} as any)
const DashVaultRoute = DashVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashRoute,
} as any)
const DashUsenetRoute = DashUsenetRouteImport.update({
  id: '/usenet',
  path: '/usenet',
  getParentRoute: () => DashRoute,
} as any)
const DashTorrentRoute = DashTorrentRouteImport.update({
  id: '/torrent',
  path: '/torrent',
  getParentRoute: () => DashRoute,
} as any)
const DashSyncRoute = DashSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashProxyRoute = DashProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => DashRoute,
} as any)
const DashLoginRoute = DashLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashRoute,
} as any)
const DashListsRoute = DashListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => DashRoute,
} as any)
const DashVaultIndexRoute = DashVaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashVaultRoute,
} as any)
const DashUsenetIndexRoute = DashUsenetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashTorrentIndexRoute = DashTorrentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashTorrentRoute,
} as any)
const DashSyncIndexRoute = DashSyncIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashSyncRoute,
} as any)
const DashSettingsIndexRoute = DashSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashSettingsRoute,
} as any)
const DashListsIndexRoute = DashListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashListsRoute,
} as any)
const DashVaultTraktAccountsRoute = DashVaultTraktAccountsRouteImport.update({
  id: '/trakt-accounts',
  path: '/trakt-accounts',
  getParentRoute: () => DashVaultRoute,
} as any)
const DashVaultStremioAccountsRoute =
  DashVaultStremioAccountsRouteImport.update({
    id: '/stremio-accounts',
    path: '/stremio-accounts',
    getParentRoute: () => DashVaultRoute,
  } as any)
const DashUsenetServersRoute = DashUsenetServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashUsenetNzbQueueRoute = DashUsenetNzbQueueRouteImport.update({
  id: '/nzb-queue',
  path: '/nzb-queue',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashUsenetNzbInspectorRoute = DashUsenetNzbInspectorRouteImport.update({
  id: '/nzb-inspector',
  path: '/nzb-inspector',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashUsenetNzbRoute = DashUsenetNzbRouteImport.update({
  id: '/nzb',
  path: '/nzb',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashUsenetIndexersRoute = DashUsenetIndexersRouteImport.update({
  id: '/indexers',
  path: '/indexers',
  getParentRoute: () => DashUsenetRoute,
} as any)
const DashTorrentTorznabIndexersRoute =
  DashTorrentTorznabIndexersRouteImport.update({
    id: '/torznab-indexers',
    path: '/torznab-indexers',
    getParentRoute: () => DashTorrentRoute,
  } as any)
const DashTorrentSyncInfoRoute = DashTorrentSyncInfoRouteImport.update({
  id: '/sync-info',
  path: '/sync-info',
  getParentRoute: () => DashTorrentRoute,
} as any)
const DashTorrentInfoRoute = DashTorrentInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DashTorrentRoute,
} as any)
const DashSyncStremioTraktRoute = DashSyncStremioTraktRouteImport.update({
  id: '/stremio-trakt',
  path: '/stremio-trakt',
  getParentRoute: () => DashSyncRoute,
} as any)
const DashSyncStremioStremioRoute = DashSyncStremioStremioRouteImport.update({
  id: '/stremio-stremio',
  path: '/stremio-stremio',
  getParentRoute: () => DashSyncRoute,
} as any)
const DashSettingsRatelimitConfigsRoute =
  DashSettingsRatelimitConfigsRouteImport.update({
    id: '/ratelimit-configs',
    path: '/ratelimit-configs',
    getParentRoute: () => DashSettingsRoute,
  } as any)
const DashSettingsMaintenanceRoute = DashSettingsMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashSettingsRoute,
} as any)
const DashSettingsJackettRoute = DashSettingsJackettRouteImport.update({
  id: '/jackett',
  path: '/jackett',
  getParentRoute: () => DashSettingsRoute,
} as any)
const DashSettingsConfigRoute = DashSettingsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/proxy': typeof DashProxyRoute
  '/dash/settings': typeof DashSettingsRouteWithChildren
  '/dash/sync': typeof DashSyncRouteWithChildren
  '/dash/torrent': typeof DashTorrentRouteWithChildren
  '/dash/usenet': typeof DashUsenetRouteWithChildren
  '/dash/vault': typeof DashVaultRouteWithChildren
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/settings/config': typeof DashSettingsConfigRoute
  '/dash/settings/jackett': typeof DashSettingsJackettRoute
  '/dash/settings/maintenance': typeof DashSettingsMaintenanceRoute
  '/dash/settings/ratelimit-configs': typeof DashSettingsRatelimitConfigsRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrent/info': typeof DashTorrentInfoRoute
  '/dash/torrent/sync-info': typeof DashTorrentSyncInfoRoute
  '/dash/torrent/torznab-indexers': typeof DashTorrentTorznabIndexersRoute
  '/dash/usenet/indexers': typeof DashUsenetIndexersRoute
  '/dash/usenet/nzb': typeof DashUsenetNzbRoute
  '/dash/usenet/nzb-inspector': typeof DashUsenetNzbInspectorRoute
  '/dash/usenet/nzb-queue': typeof DashUsenetNzbQueueRoute
  '/dash/usenet/servers': typeof DashUsenetServersRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists/': typeof DashListsIndexRoute
  '/dash/settings/': typeof DashSettingsIndexRoute
  '/dash/sync/': typeof DashSyncIndexRoute
  '/dash/torrent/': typeof DashTorrentIndexRoute
  '/dash/usenet/': typeof DashUsenetIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRoutesByTo {
  '/dash/login': typeof DashLoginRoute
  '/dash/proxy': typeof DashProxyRoute
  '/dash/workers': typeof DashWorkersRoute
  '/dash': typeof DashIndexRoute
  '/dash/settings/config': typeof DashSettingsConfigRoute
  '/dash/settings/jackett': typeof DashSettingsJackettRoute
  '/dash/settings/maintenance': typeof DashSettingsMaintenanceRoute
  '/dash/settings/ratelimit-configs': typeof DashSettingsRatelimitConfigsRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrent/info': typeof DashTorrentInfoRoute
  '/dash/torrent/sync-info': typeof DashTorrentSyncInfoRoute
  '/dash/torrent/torznab-indexers': typeof DashTorrentTorznabIndexersRoute
  '/dash/usenet/indexers': typeof DashUsenetIndexersRoute
  '/dash/usenet/nzb': typeof DashUsenetNzbRoute
  '/dash/usenet/nzb-inspector': typeof DashUsenetNzbInspectorRoute
  '/dash/usenet/nzb-queue': typeof DashUsenetNzbQueueRoute
  '/dash/usenet/servers': typeof DashUsenetServersRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists': typeof DashListsIndexRoute
  '/dash/settings': typeof DashSettingsIndexRoute
  '/dash/sync': typeof DashSyncIndexRoute
  '/dash/torrent': typeof DashTorrentIndexRoute
  '/dash/usenet': typeof DashUsenetIndexRoute
  '/dash/vault': typeof DashVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/proxy': typeof DashProxyRoute
  '/dash/settings': typeof DashSettingsRouteWithChildren
  '/dash/sync': typeof DashSyncRouteWithChildren
  '/dash/torrent': typeof DashTorrentRouteWithChildren
  '/dash/usenet': typeof DashUsenetRouteWithChildren
  '/dash/vault': typeof DashVaultRouteWithChildren
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/settings/config': typeof DashSettingsConfigRoute
  '/dash/settings/jackett': typeof DashSettingsJackettRoute
  '/dash/settings/maintenance': typeof DashSettingsMaintenanceRoute
  '/dash/settings/ratelimit-configs': typeof DashSettingsRatelimitConfigsRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrent/info': typeof DashTorrentInfoRoute
  '/dash/torrent/sync-info': typeof DashTorrentSyncInfoRoute
  '/dash/torrent/torznab-indexers': typeof DashTorrentTorznabIndexersRoute
  '/dash/usenet/indexers': typeof DashUsenetIndexersRoute
  '/dash/usenet/nzb': typeof DashUsenetNzbRoute
  '/dash/usenet/nzb-inspector': typeof DashUsenetNzbInspectorRoute
  '/dash/usenet/nzb-queue': typeof DashUsenetNzbQueueRoute
  '/dash/usenet/servers': typeof DashUsenetServersRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists/': typeof DashListsIndexRoute
  '/dash/settings/': typeof DashSettingsIndexRoute
  '/dash/sync/': typeof DashSyncIndexRoute
  '/dash/torrent/': typeof DashTorrentIndexRoute
  '/dash/usenet/': typeof DashUsenetIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/proxy'
    | '/dash/settings'
    | '/dash/sync'
    | '/dash/torrent'
    | '/dash/usenet'
    | '/dash/vault'
    | '/dash/workers'
    | '/dash/'
    | '/dash/settings/config'
    | '/dash/settings/jackett'
    | '/dash/settings/maintenance'
    | '/dash/settings/ratelimit-configs'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrent/info'
    | '/dash/torrent/sync-info'
    | '/dash/torrent/torznab-indexers'
    | '/dash/usenet/indexers'
    | '/dash/usenet/nzb'
    | '/dash/usenet/nzb-inspector'
    | '/dash/usenet/nzb-queue'
    | '/dash/usenet/servers'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists/'
    | '/dash/settings/'
    | '/dash/sync/'
    | '/dash/torrent/'
    | '/dash/usenet/'
    | '/dash/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dash/login'
    | '/dash/proxy'
    | '/dash/workers'
    | '/dash'
    | '/dash/settings/config'
    | '/dash/settings/jackett'
    | '/dash/settings/maintenance'
    | '/dash/settings/ratelimit-configs'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrent/info'
    | '/dash/torrent/sync-info'
    | '/dash/torrent/torznab-indexers'
    | '/dash/usenet/indexers'
    | '/dash/usenet/nzb'
    | '/dash/usenet/nzb-inspector'
    | '/dash/usenet/nzb-queue'
    | '/dash/usenet/servers'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists'
    | '/dash/settings'
    | '/dash/sync'
    | '/dash/torrent'
    | '/dash/usenet'
    | '/dash/vault'
  id:
    | '__root__'
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/proxy'
    | '/dash/settings'
    | '/dash/sync'
    | '/dash/torrent'
    | '/dash/usenet'
    | '/dash/vault'
    | '/dash/workers'
    | '/dash/'
    | '/dash/settings/config'
    | '/dash/settings/jackett'
    | '/dash/settings/maintenance'
    | '/dash/settings/ratelimit-configs'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrent/info'
    | '/dash/torrent/sync-info'
    | '/dash/torrent/torznab-indexers'
    | '/dash/usenet/indexers'
    | '/dash/usenet/nzb'
    | '/dash/usenet/nzb-inspector'
    | '/dash/usenet/nzb-queue'
    | '/dash/usenet/servers'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists/'
    | '/dash/settings/'
    | '/dash/sync/'
    | '/dash/torrent/'
    | '/dash/usenet/'
    | '/dash/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/workers': {
      id: '/dash/workers'
      path: '/workers'
      fullPath: '/dash/workers'
      preLoaderRoute: typeof DashWorkersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/vault': {
      id: '/dash/vault'
      path: '/vault'
      fullPath: '/dash/vault'
      preLoaderRoute: typeof DashVaultRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/usenet': {
      id: '/dash/usenet'
      path: '/usenet'
      fullPath: '/dash/usenet'
      preLoaderRoute: typeof DashUsenetRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/torrent': {
      id: '/dash/torrent'
      path: '/torrent'
      fullPath: '/dash/torrent'
      preLoaderRoute: typeof DashTorrentRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/sync': {
      id: '/dash/sync'
      path: '/sync'
      fullPath: '/dash/sync'
      preLoaderRoute: typeof DashSyncRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/proxy': {
      id: '/dash/proxy'
      path: '/proxy'
      fullPath: '/dash/proxy'
      preLoaderRoute: typeof DashProxyRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/login': {
      id: '/dash/login'
      path: '/login'
      fullPath: '/dash/login'
      preLoaderRoute: typeof DashLoginRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/lists': {
      id: '/dash/lists'
      path: '/lists'
      fullPath: '/dash/lists'
      preLoaderRoute: typeof DashListsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/vault/': {
      id: '/dash/vault/'
      path: '/'
      fullPath: '/dash/vault/'
      preLoaderRoute: typeof DashVaultIndexRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/usenet/': {
      id: '/dash/usenet/'
      path: '/'
      fullPath: '/dash/usenet/'
      preLoaderRoute: typeof DashUsenetIndexRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/torrent/': {
      id: '/dash/torrent/'
      path: '/'
      fullPath: '/dash/torrent/'
      preLoaderRoute: typeof DashTorrentIndexRouteImport
      parentRoute: typeof DashTorrentRoute
    }
    '/dash/sync/': {
      id: '/dash/sync/'
      path: '/'
      fullPath: '/dash/sync/'
      preLoaderRoute: typeof DashSyncIndexRouteImport
      parentRoute: typeof DashSyncRoute
    }
    '/dash/settings/': {
      id: '/dash/settings/'
      path: '/'
      fullPath: '/dash/settings/'
      preLoaderRoute: typeof DashSettingsIndexRouteImport
      parentRoute: typeof DashSettingsRoute
    }
    '/dash/lists/': {
      id: '/dash/lists/'
      path: '/'
      fullPath: '/dash/lists/'
      preLoaderRoute: typeof DashListsIndexRouteImport
      parentRoute: typeof DashListsRoute
    }
    '/dash/vault/trakt-accounts': {
      id: '/dash/vault/trakt-accounts'
      path: '/trakt-accounts'
      fullPath: '/dash/vault/trakt-accounts'
      preLoaderRoute: typeof DashVaultTraktAccountsRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/vault/stremio-accounts': {
      id: '/dash/vault/stremio-accounts'
      path: '/stremio-accounts'
      fullPath: '/dash/vault/stremio-accounts'
      preLoaderRoute: typeof DashVaultStremioAccountsRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/usenet/servers': {
      id: '/dash/usenet/servers'
      path: '/servers'
      fullPath: '/dash/usenet/servers'
      preLoaderRoute: typeof DashUsenetServersRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/usenet/nzb-queue': {
      id: '/dash/usenet/nzb-queue'
      path: '/nzb-queue'
      fullPath: '/dash/usenet/nzb-queue'
      preLoaderRoute: typeof DashUsenetNzbQueueRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/usenet/nzb-inspector': {
      id: '/dash/usenet/nzb-inspector'
      path: '/nzb-inspector'
      fullPath: '/dash/usenet/nzb-inspector'
      preLoaderRoute: typeof DashUsenetNzbInspectorRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/usenet/nzb': {
      id: '/dash/usenet/nzb'
      path: '/nzb'
      fullPath: '/dash/usenet/nzb'
      preLoaderRoute: typeof DashUsenetNzbRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/usenet/indexers': {
      id: '/dash/usenet/indexers'
      path: '/indexers'
      fullPath: '/dash/usenet/indexers'
      preLoaderRoute: typeof DashUsenetIndexersRouteImport
      parentRoute: typeof DashUsenetRoute
    }
    '/dash/torrent/torznab-indexers': {
      id: '/dash/torrent/torznab-indexers'
      path: '/torznab-indexers'
      fullPath: '/dash/torrent/torznab-indexers'
      preLoaderRoute: typeof DashTorrentTorznabIndexersRouteImport
      parentRoute: typeof DashTorrentRoute
    }
    '/dash/torrent/sync-info': {
      id: '/dash/torrent/sync-info'
      path: '/sync-info'
      fullPath: '/dash/torrent/sync-info'
      preLoaderRoute: typeof DashTorrentSyncInfoRouteImport
      parentRoute: typeof DashTorrentRoute
    }
    '/dash/torrent/info': {
      id: '/dash/torrent/info'
      path: '/info'
      fullPath: '/dash/torrent/info'
      preLoaderRoute: typeof DashTorrentInfoRouteImport
      parentRoute: typeof DashTorrentRoute
    }
    '/dash/sync/stremio-trakt': {
      id: '/dash/sync/stremio-trakt'
      path: '/stremio-trakt'
      fullPath: '/dash/sync/stremio-trakt'
      preLoaderRoute: typeof DashSyncStremioTraktRouteImport
      parentRoute: typeof DashSyncRoute
    }
    '/dash/sync/stremio-stremio': {
      id: '/dash/sync/stremio-stremio'
      path: '/stremio-stremio'
      fullPath: '/dash/sync/stremio-stremio'
      preLoaderRoute: typeof DashSyncStremioStremioRouteImport
      parentRoute: typeof DashSyncRoute
    }
    '/dash/settings/ratelimit-configs': {
      id: '/dash/settings/ratelimit-configs'
      path: '/ratelimit-configs'
      fullPath: '/dash/settings/ratelimit-configs'
      preLoaderRoute: typeof DashSettingsRatelimitConfigsRouteImport
      parentRoute: typeof DashSettingsRoute
    }
    '/dash/settings/maintenance': {
      id: '/dash/settings/maintenance'
      path: '/maintenance'
      fullPath: '/dash/settings/maintenance'
      preLoaderRoute: typeof DashSettingsMaintenanceRouteImport
      parentRoute: typeof DashSettingsRoute
    }
    '/dash/settings/jackett': {
      id: '/dash/settings/jackett'
      path: '/jackett'
      fullPath: '/dash/settings/jackett'
      preLoaderRoute: typeof DashSettingsJackettRouteImport
      parentRoute: typeof DashSettingsRoute
    }
    '/dash/settings/config': {
      id: '/dash/settings/config'
      path: '/config'
      fullPath: '/dash/settings/config'
      preLoaderRoute: typeof DashSettingsConfigRouteImport
      parentRoute: typeof DashSettingsRoute
    }
  }
}

interface DashListsRouteChildren {
  DashListsIndexRoute: typeof DashListsIndexRoute
}

const DashListsRouteChildren: DashListsRouteChildren = {
  DashListsIndexRoute: DashListsIndexRoute,
}

const DashListsRouteWithChildren = DashListsRoute._addFileChildren(
  DashListsRouteChildren,
)

interface DashSettingsRouteChildren {
  DashSettingsConfigRoute: typeof DashSettingsConfigRoute
  DashSettingsJackettRoute: typeof DashSettingsJackettRoute
  DashSettingsMaintenanceRoute: typeof DashSettingsMaintenanceRoute
  DashSettingsRatelimitConfigsRoute: typeof DashSettingsRatelimitConfigsRoute
  DashSettingsIndexRoute: typeof DashSettingsIndexRoute
}

const DashSettingsRouteChildren: DashSettingsRouteChildren = {
  DashSettingsConfigRoute: DashSettingsConfigRoute,
  DashSettingsJackettRoute: DashSettingsJackettRoute,
  DashSettingsMaintenanceRoute: DashSettingsMaintenanceRoute,
  DashSettingsRatelimitConfigsRoute: DashSettingsRatelimitConfigsRoute,
  DashSettingsIndexRoute: DashSettingsIndexRoute,
}

const DashSettingsRouteWithChildren = DashSettingsRoute._addFileChildren(
  DashSettingsRouteChildren,
)

interface DashSyncRouteChildren {
  DashSyncStremioStremioRoute: typeof DashSyncStremioStremioRoute
  DashSyncStremioTraktRoute: typeof DashSyncStremioTraktRoute
  DashSyncIndexRoute: typeof DashSyncIndexRoute
}

const DashSyncRouteChildren: DashSyncRouteChildren = {
  DashSyncStremioStremioRoute: DashSyncStremioStremioRoute,
  DashSyncStremioTraktRoute: DashSyncStremioTraktRoute,
  DashSyncIndexRoute: DashSyncIndexRoute,
}

const DashSyncRouteWithChildren = DashSyncRoute._addFileChildren(
  DashSyncRouteChildren,
)

interface DashTorrentRouteChildren {
  DashTorrentInfoRoute: typeof DashTorrentInfoRoute
  DashTorrentSyncInfoRoute: typeof DashTorrentSyncInfoRoute
  DashTorrentTorznabIndexersRoute: typeof DashTorrentTorznabIndexersRoute
  DashTorrentIndexRoute: typeof DashTorrentIndexRoute
}

const DashTorrentRouteChildren: DashTorrentRouteChildren = {
  DashTorrentInfoRoute: DashTorrentInfoRoute,
  DashTorrentSyncInfoRoute: DashTorrentSyncInfoRoute,
  DashTorrentTorznabIndexersRoute: DashTorrentTorznabIndexersRoute,
  DashTorrentIndexRoute: DashTorrentIndexRoute,
}

const DashTorrentRouteWithChildren = DashTorrentRoute._addFileChildren(
  DashTorrentRouteChildren,
)

interface DashUsenetRouteChildren {
  DashUsenetIndexersRoute: typeof DashUsenetIndexersRoute
  DashUsenetNzbRoute: typeof DashUsenetNzbRoute
  DashUsenetNzbInspectorRoute: typeof DashUsenetNzbInspectorRoute
  DashUsenetNzbQueueRoute: typeof DashUsenetNzbQueueRoute
  DashUsenetServersRoute: typeof DashUsenetServersRoute
  DashUsenetIndexRoute: typeof DashUsenetIndexRoute
}

const DashUsenetRouteChildren: DashUsenetRouteChildren = {
  DashUsenetIndexersRoute: DashUsenetIndexersRoute,
  DashUsenetNzbRoute: DashUsenetNzbRoute,
  DashUsenetNzbInspectorRoute: DashUsenetNzbInspectorRoute,
  DashUsenetNzbQueueRoute: DashUsenetNzbQueueRoute,
  DashUsenetServersRoute: DashUsenetServersRoute,
  DashUsenetIndexRoute: DashUsenetIndexRoute,
}

const DashUsenetRouteWithChildren = DashUsenetRoute._addFileChildren(
  DashUsenetRouteChildren,
)

interface DashVaultRouteChildren {
  DashVaultStremioAccountsRoute: typeof DashVaultStremioAccountsRoute
  DashVaultTraktAccountsRoute: typeof DashVaultTraktAccountsRoute
  DashVaultIndexRoute: typeof DashVaultIndexRoute
}

const DashVaultRouteChildren: DashVaultRouteChildren = {
  DashVaultStremioAccountsRoute: DashVaultStremioAccountsRoute,
  DashVaultTraktAccountsRoute: DashVaultTraktAccountsRoute,
  DashVaultIndexRoute: DashVaultIndexRoute,
}

const DashVaultRouteWithChildren = DashVaultRoute._addFileChildren(
  DashVaultRouteChildren,
)

interface DashRouteChildren {
  DashListsRoute: typeof DashListsRouteWithChildren
  DashLoginRoute: typeof DashLoginRoute
  DashProxyRoute: typeof DashProxyRoute
  DashSettingsRoute: typeof DashSettingsRouteWithChildren
  DashSyncRoute: typeof DashSyncRouteWithChildren
  DashTorrentRoute: typeof DashTorrentRouteWithChildren
  DashUsenetRoute: typeof DashUsenetRouteWithChildren
  DashVaultRoute: typeof DashVaultRouteWithChildren
  DashWorkersRoute: typeof DashWorkersRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashListsRoute: DashListsRouteWithChildren,
  DashLoginRoute: DashLoginRoute,
  DashProxyRoute: DashProxyRoute,
  DashSettingsRoute: DashSettingsRouteWithChildren,
  DashSyncRoute: DashSyncRouteWithChildren,
  DashTorrentRoute: DashTorrentRouteWithChildren,
  DashUsenetRoute: DashUsenetRouteWithChildren,
  DashVaultRoute: DashVaultRouteWithChildren,
  DashWorkersRoute: DashWorkersRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
